.travis.yml
pom.xml

add travis ci and codecov

---

README.md

modify  description

---

CONTRIBUTING.md

add contribution

---

sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/bootstrap/Launcher.java

fix error entry method description when run in ide

---

sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/bootstrap/EntryMethod.java
sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/bootstrap/SofaArkBootstrap.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/PluginModel.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/pipeline/DeployBizStage.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/pipeline/HandleArchiveStage.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/pipeline/StandardPipeline.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/ArkServiceContainer.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/ClassloaderServiceImpl.java
sofa-ark-parent/core/common/src/main/java/com/alipay/sofa/ark/common/thread/LaunchRunner.java
sofa-ark-parent/support/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/ArkApplicationStartListener.java

catch exception to throwable

---

README.md

fix the grammar errors on the readme

fix grammar error

---

sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/PluginModel.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/pipeline/HandleArchiveStage.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/BizClassLoader.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/ClassloaderServiceImpl.java
sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/classloader/BizClassloaderTest.java
sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/classloader/PluginClassloaderTest.java
sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/registry/RegistryServiceTest.java
sofa-ark-parent/core/common/src/main/java/com/alipay/sofa/ark/common/util/StringUtils.java
sofa-ark-parent/core/common/src/test/java/com/alipay/sofa/ark/common/util/StringUtilsTest.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/model/Biz.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/service/classloader/ClassloaderService.java
sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/common/DelegateArkContainer.java
sofa-ark-parent/support/ark-tools/src/main/java/com/alipay/sofa/ark/tools/Repackager.java

Support deny class

---

pom.xml
sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/bootstrap/Launcher.java
sofa-ark-parent/support/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/runner/ArkBootRunner.java
sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/common/DelegateArkContainer.java

- change java doc to make it correct
- move javadoc-plugin to default config

change java doc and ci scripts

---

pom.xml
sofa-ark-bom/pom.xml
sofa-ark-parent/assembly/pom.xml
sofa-ark-parent/core-impl/archive/pom.xml
sofa-ark-parent/core-impl/container/pom.xml
sofa-ark-parent/core-impl/pom.xml
sofa-ark-parent/core/common/pom.xml
sofa-ark-parent/core/exception/pom.xml
sofa-ark-parent/core/pom.xml
sofa-ark-parent/core/spi/pom.xml
sofa-ark-parent/pom.xml
sofa-ark-parent/support/ark-maven-plugin/pom.xml
sofa-ark-parent/support/ark-plugin-maven-plugin/pom.xml
sofa-ark-parent/support/ark-springboot-starter/pom.xml
sofa-ark-parent/support/ark-support-starter/pom.xml
sofa-ark-parent/support/ark-tools/pom.xml
sofa-ark-parent/support/pom.xml
sofa-ark-samples/pom.xml
sofa-ark-samples/sample-ark-plugin/README.md
sofa-ark-samples/sample-ark-plugin/README_EN.md
sofa-ark-samples/sample-ark-plugin/common/pom.xml
sofa-ark-samples/sample-ark-plugin/plugin/pom.xml
sofa-ark-samples/sample-ark-plugin/pom.xml
sofa-ark-samples/sample-springboot-ark/README.md
sofa-ark-samples/sample-springboot-ark/README_EN.md
sofa-ark-samples/sample-springboot-ark/pom.xml

upgrade 0.4.0

---

sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/ArkContainer.java

register shutdown hook , make sure ArkContainer responds to unix kill command(Unless the -9 option is added).

register shutdown hook

---

pom.xml
sofa-ark-bom/pom.xml
sofa-ark-parent/assembly/pom.xml
sofa-ark-parent/core-impl/archive/pom.xml
sofa-ark-parent/core-impl/container/pom.xml
sofa-ark-parent/core-impl/pom.xml
sofa-ark-parent/core/common/pom.xml
sofa-ark-parent/core/exception/pom.xml
sofa-ark-parent/core/pom.xml
sofa-ark-parent/core/spi/pom.xml
sofa-ark-parent/pom.xml
sofa-ark-parent/support/ark-maven-plugin/pom.xml
sofa-ark-parent/support/ark-plugin-maven-plugin/pom.xml
sofa-ark-parent/support/ark-springboot-starter/pom.xml
sofa-ark-parent/support/ark-support-starter/pom.xml
sofa-ark-parent/support/ark-tools/pom.xml
sofa-ark-parent/support/pom.xml
sofa-ark-samples/pom.xml
sofa-ark-samples/sample-ark-plugin/README.md
sofa-ark-samples/sample-ark-plugin/README_EN.md
sofa-ark-samples/sample-ark-plugin/common/pom.xml
sofa-ark-samples/sample-ark-plugin/plugin/pom.xml
sofa-ark-samples/sample-ark-plugin/pom.xml
sofa-ark-samples/sample-springboot-ark/README.md
sofa-ark-samples/sample-springboot-ark/README_EN.md
sofa-ark-samples/sample-springboot-ark/pom.xml

upgrade version 0.4.1

---

sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
sofa-ark-parent/support/ark-tools/src/main/java/com/alipay/sofa/ark/tools/Repackager.java

Fix a bug that package provided jar into the ark biz

---

sofa-ark-parent/core/common/src/main/java/com/alipay/sofa/ark/common/util/EnvironmentUtils.java
sofa-ark-parent/support/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/listener/ArkApplicationStartListener.java

Remove logging properties.

---

pom.xml
sofa-ark-bom/pom.xml
sofa-ark-parent/assembly/pom.xml
sofa-ark-parent/core-impl/archive/pom.xml
sofa-ark-parent/core-impl/container/pom.xml
sofa-ark-parent/core-impl/pom.xml
sofa-ark-parent/core/common/pom.xml
sofa-ark-parent/core/common/src/main/java/com/alipay/sofa/ark/common/util/EnvironmentUtils.java
sofa-ark-parent/core/exception/pom.xml
sofa-ark-parent/core/pom.xml
sofa-ark-parent/core/spi/pom.xml
sofa-ark-parent/pom.xml
sofa-ark-parent/support/ark-maven-plugin/pom.xml
sofa-ark-parent/support/ark-plugin-maven-plugin/pom.xml
sofa-ark-parent/support/ark-springboot-starter/pom.xml
sofa-ark-parent/support/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/listener/ArkApplicationStartListener.java
sofa-ark-parent/support/ark-support-starter/pom.xml
sofa-ark-parent/support/ark-tools/pom.xml
sofa-ark-parent/support/pom.xml
sofa-ark-samples/pom.xml
sofa-ark-samples/sample-ark-plugin/README.md
sofa-ark-samples/sample-ark-plugin/README_EN.md
sofa-ark-samples/sample-ark-plugin/common/pom.xml
sofa-ark-samples/sample-ark-plugin/plugin/pom.xml
sofa-ark-samples/sample-ark-plugin/pom.xml
sofa-ark-samples/sample-springboot-ark/README.md
sofa-ark-samples/sample-springboot-ark/README_EN.md
sofa-ark-samples/sample-springboot-ark/pom.xml

Upgrade to v0.4.1. Prepare to release.

Upgrade release

---

sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/AbstractClasspathClassloader.java
sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/classloader/ClassloaderConcurrencyTest.java
sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/testdata/classloader/ClassloaderTestClass.java

fix classloader concurrency bug

---

sofa-ark-bom/pom.xml
sofa-ark-parent/support/ark-springboot-starter/pom.xml

Remove spring boot version management

---

sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/bootstrap/AbstractLauncher.java
sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/bootstrap/ClasspathLauncher.java
sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/bootstrap/ClasspathLauncherTest.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/ArkContainer.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/pipeline/DeployBizStage.java
sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/ArkContainerTest.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/argument/CommandArgument.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/argument/LaunchCommand.java
sofa-ark-parent/core/spi/src/test/java/com/alipay/sofa/ark/spi/argument/LaunchCommandTest.java

Ark biz would not been launched when run test method. This pr fix it and remove the TEST MODE.

Remove special test logic 

---

sofa-ark-parent/support/ark-plugin-maven-plugin/src/main/java/com/alipay/sofa/ark/plugin/mojo/ArkPluginMojo.java
sofa-ark-parent/support/ark-plugin-maven-plugin/src/test/java/com/alipay/sofa/ark/plugin/mojo/test/ArkPluginMojoTest.java

#153 
支持 ark plugin 打包时，将 plugin 模块的类以 .class 文件打入。

support package plugin class

---

sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/ArkContainer.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java

https://github.com/alipay/sofa-hessian/issues/38

Compatible sofa hessian4

---

sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/archive/AbstractArchive.java

fix unnecessary grow of list capacity

---

sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
sofa-ark-parent/support/ark-tools/src/main/java/com/alipay/sofa/ark/tools/Repackager.java

add support for skip ark executable

---

sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/bootstrap/BaseExecutableArchiveLauncher.java
sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/archive/ExplodedArchive.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/ArkContainer.java

support running from folder

---

sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/jar/ZipInflaterInputStream.java

optimized ZipInflaterInputStream

---

sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/bootstrap/BaseExecutableArchiveLauncher.java
sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/archive/ExplodedArchive.java
sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/jar/ZipInflaterInputStream.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/ArkContainer.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/PluginModel.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/ClassLoaderServiceImpl.java
sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/classloader/BizClassLoaderTest.java
sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/classloader/PluginClassLoaderTest.java
sofa-ark-parent/core/common/src/main/java/com/alipay/sofa/ark/common/util/ParseUtils.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/model/BizInfo.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/model/Plugin.java

support export stem resource and deny-import stem resource

---

pom.xml
sofa-ark-bom/pom.xml
sofa-ark-parent/assembly/pom.xml
sofa-ark-parent/core-impl/archive/pom.xml
sofa-ark-parent/core-impl/container/pom.xml
sofa-ark-parent/core-impl/pom.xml
sofa-ark-parent/core/api/pom.xml
sofa-ark-parent/core/common/pom.xml
sofa-ark-parent/core/exception/pom.xml
sofa-ark-parent/core/pom.xml
sofa-ark-parent/core/spi/pom.xml
sofa-ark-parent/pom.xml
sofa-ark-parent/support/ark-maven-plugin/pom.xml
sofa-ark-parent/support/ark-plugin-maven-plugin/pom.xml
sofa-ark-parent/support/ark-plugin-maven-plugin/src/main/resources/META-INF/maven/plugin.xml
sofa-ark-parent/support/ark-springboot-integration/ark-common-springboot/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
sofa-ark-parent/support/ark-support-starter/pom.xml
sofa-ark-parent/support/ark-tools/pom.xml
sofa-ark-parent/support/pom.xml
sofa-ark-plugin/config-ark-plugin/pom.xml
sofa-ark-plugin/web-ark-plugin/pom.xml
sofa-ark-samples/pom.xml
sofa-ark-samples/sample-ark-plugin/common/pom.xml
sofa-ark-samples/sample-ark-plugin/plugin/pom.xml
sofa-ark-samples/sample-ark-plugin/pom.xml
sofa-ark-samples/sample-springboot-ark/pom.xml

prepare-to-release-1.0.0

---

sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/AbstractClasspathClassLoader.java

change log level when resolve exported class

---

sofa-ark-parent/support/ark-springboot-integration/ark-common-springboot/src/main/java/com/alipay/sofa/ark/springboot/condition/OnArkEnabled.java

OnArkEnabled support PluginClassLoader

---

sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/AbstractClasspathClassLoader.java
sofa-ark-parent/support/ark-springboot-integration/ark-common-springboot/src/main/java/com/alipay/sofa/ark/springboot/condition/OnArkEnabled.java

Handle ark classes when get class resource

---

sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/biz/BizCommandProvider.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/session/NettyTelnetServer.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java

Support telnet quit

---

sofa-ark-parent/core/api/src/main/java/com/alipay/sofa/ark/api/ArkClient.java

fix issue 315

---

sofa-ark-bom/pom.xml
sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/DirectoryContainerArchive.java

update netty to 4.1.42.Fianl

---

sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/PluginModel.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/ClassLoaderServiceImpl.java
sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/classloader/ClassLoaderServiceTest.java
sofa-ark-parent/core/common/src/main/java/com/alipay/sofa/ark/common/util/ParseUtils.java
sofa-ark-parent/core/common/src/test/java/com/alipay/sofa/ark/common/util/ParseUtilsTest.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/model/BizInfo.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/model/Plugin.java

support match by file type

---

sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/PluginModel.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/pipeline/DeployBizStage.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/ArkServiceContainer.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/event/EventAdminServiceImpl.java
sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/api/ArkClientTest.java
sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/event/EventAdminServiceTest.java
sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/event/EventTest.java
sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/event/GlobalEventHandlerTest.java
sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/event/MultiEventTest.java
sofa-ark-parent/core/api/src/main/java/com/alipay/sofa/ark/api/ArkClient.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/event/AbstractArkEvent.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/event/AfterFinishDeployEvent.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/event/AfterFinishStartupEvent.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/event/biz/AfterBizStartupEvent.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/event/biz/AfterBizStopEvent.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/event/biz/AfterBizSwitchEvent.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/event/biz/BeforeBizStartupEvent.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/event/biz/BeforeBizStopEvent.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/event/biz/BeforeBizSwitchEvent.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/event/plugin/AfterPluginStartupEvent.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/event/plugin/AfterPluginStopEvent.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/event/plugin/BeforePluginStartupEvent.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/event/plugin/BeforePluginStopEvent.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/service/event/EventHandler.java
sofa-ark-plugin/config-ark-plugin/src/main/java/com/alipay/sofa/ark/config/zk/ZookeeperConfigActivator.java

optimized event profile

---

pom.xml
sofa-ark-bom/pom.xml
sofa-ark-parent/assembly/pom.xml
sofa-ark-parent/core-impl/archive/pom.xml
sofa-ark-parent/core-impl/container/pom.xml
sofa-ark-parent/core-impl/pom.xml
sofa-ark-parent/core/api/pom.xml
sofa-ark-parent/core/common/pom.xml
sofa-ark-parent/core/exception/pom.xml
sofa-ark-parent/core/pom.xml
sofa-ark-parent/core/spi/pom.xml
sofa-ark-parent/pom.xml
sofa-ark-parent/support/ark-maven-plugin/pom.xml
sofa-ark-parent/support/ark-plugin-maven-plugin/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-common-springboot/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
sofa-ark-parent/support/ark-support-starter/pom.xml
sofa-ark-parent/support/ark-tools/pom.xml
sofa-ark-parent/support/pom.xml
sofa-ark-plugin/config-ark-plugin/pom.xml
sofa-ark-plugin/web-ark-plugin/pom.xml

upgrade version 1.1.1-SNAPSHOT

---

sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/event/EventAdminServiceImpl.java
sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/biz/BizCommandProviderTest.java
sofa-ark-parent/core/api/src/main/java/com/alipay/sofa/ark/api/ArkClient.java

https://github.com/sofastack/sofa-ark/issues/343

biz unregister improvement

---

sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/AbstractClasspathClassLoader.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/AgentClassLoader.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/BizClassLoader.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/JDKDelegateClassLoader.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/PluginClassLoader.java

classloader registerAsParallelCapable

---

sofa-ark-parent/core/common/src/main/resources/com/alipay/sofa/ark/log/log4j/log-conf.xml
sofa-ark-parent/core/common/src/main/resources/com/alipay/sofa/ark/log/log4j2/log-conf.xml
sofa-ark-parent/core/common/src/main/resources/com/alipay/sofa/ark/log/logback/log-conf.xml

fix: https://github.com/sofastack/sofa-ark/issues/361

Add sofa-common-tools log4j and log4j2 config file

---

sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/biz/BizCommandProvider.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/session/NettyTelnetServer.java
sofa-ark-parent/core/common/src/main/java/com/alipay/sofa/ark/common/util/EnvironmentUtils.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java

* 1、add  sofa.ark.telnet.security.enable config to open with security mode.
* 2、when security mode opened, disable to use biz -i & biz -u
* 3、when security mode opened, it only receives connect requests from the localhost.

support security mode

---

sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java

fix-web-stop

---

sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/api/ArkClientTest.java
sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/event/EventTest.java

provide BEFORE-RECYCLE-BIZ event test case

provide BEFORE-RECYCLE-BIZ event test case

---

sofa-ark-parent/core/api/src/main/java/com/alipay/sofa/ark/api/ArkClient.java

fix-biz-stop

---

sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/web/ArkTomcatServletWebServerFactory.java

fix-getContextWebOnTest

---

.github/workflows/build.yml
sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/pom.xml

Describe the idea and modifications you've done. 

Migrate CI provider from Travis CI to Github Actions.

---

pom.xml
sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/ExecutableArkBizJar.java
sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/JarBizArchive.java
sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/JarPluginArchive.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/PluginModel.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/pipeline/HandleArchiveStage.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/biz/BizFactoryServiceImpl.java
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/plugin/PluginFactoryServiceImpl.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/archive/Archive.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/archive/PluginArchive.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/service/plugin/PluginFactoryService.java
sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
sofa-ark-parent/support/ark-tools/src/main/java/com/alipay/sofa/ark/tools/Repackager.java

#390 support plugin to extension the business dependency

Support custom plugin extension

---

pom.xml
sofa-ark-bom/pom.xml
sofa-ark-parent/assembly/pom.xml
sofa-ark-parent/core-impl/archive/pom.xml
sofa-ark-parent/core-impl/container/pom.xml
sofa-ark-parent/core-impl/pom.xml
sofa-ark-parent/core/api/pom.xml
sofa-ark-parent/core/common/pom.xml
sofa-ark-parent/core/exception/pom.xml
sofa-ark-parent/core/pom.xml
sofa-ark-parent/core/spi/pom.xml
sofa-ark-parent/pom.xml
sofa-ark-parent/support/ark-maven-plugin/pom.xml
sofa-ark-parent/support/ark-plugin-maven-plugin/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-common-springboot/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
sofa-ark-parent/support/ark-support-starter/pom.xml
sofa-ark-parent/support/ark-tools/pom.xml
sofa-ark-parent/support/pom.xml
sofa-ark-plugin/config-ark-plugin/pom.xml
sofa-ark-plugin/web-ark-plugin/pom.xml

update to 2.0.1

---

pom.xml
sofa-ark-bom/pom.xml
sofa-ark-parent/assembly/pom.xml
sofa-ark-parent/core-impl/archive/pom.xml
sofa-ark-parent/core-impl/container/pom.xml
sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/injection/InjectionServiceImpl.java
sofa-ark-parent/core-impl/pom.xml
sofa-ark-parent/core/api/pom.xml
sofa-ark-parent/core/common/pom.xml
sofa-ark-parent/core/exception/pom.xml
sofa-ark-parent/core/pom.xml
sofa-ark-parent/core/spi/pom.xml
sofa-ark-parent/pom.xml
sofa-ark-parent/support/ark-maven-plugin/pom.xml
sofa-ark-parent/support/ark-plugin-maven-plugin/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-common-springboot/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/loader/CachedLaunchedURLClassLoader.java
sofa-ark-parent/support/ark-support-starter/pom.xml
sofa-ark-parent/support/ark-tools/pom.xml
sofa-ark-parent/support/pom.xml
sofa-ark-plugin/config-ark-plugin/pom.xml
sofa-ark-plugin/web-ark-plugin/pom.xml

reduce cache size

---

sofa-ark-parent/core/api/src/main/java/com/alipay/sofa/ark/api/ArkClient.java

fix early initialization for sofa-common-tools

fix early initialization for sofa-common-tools

---

sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/ext/ExtResponse.java

ExtResponse add Field "data"

---

pom.xml
sofa-ark-bom/pom.xml
sofa-ark-parent/assembly/pom.xml
sofa-ark-parent/core-impl/archive/pom.xml
sofa-ark-parent/core-impl/container/pom.xml
sofa-ark-parent/core-impl/pom.xml
sofa-ark-parent/core/api/pom.xml
sofa-ark-parent/core/common/pom.xml
sofa-ark-parent/core/exception/pom.xml
sofa-ark-parent/core/pom.xml
sofa-ark-parent/core/spi/pom.xml
sofa-ark-parent/pom.xml
sofa-ark-parent/support/ark-maven-plugin/pom.xml
sofa-ark-parent/support/ark-plugin-maven-plugin/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-common-springboot/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
sofa-ark-parent/support/ark-support-starter/pom.xml
sofa-ark-parent/support/ark-tools/pom.xml
sofa-ark-parent/support/pom.xml
sofa-ark-plugin/config-ark-plugin/pom.xml
sofa-ark-plugin/web-ark-plugin/pom.xml

update to 2.1.1

---

pom.xml
sofa-ark-bom/pom.xml
sofa-ark-parent/assembly/pom.xml
sofa-ark-parent/core-impl/archive/pom.xml
sofa-ark-parent/core-impl/container/pom.xml
sofa-ark-parent/core-impl/pom.xml
sofa-ark-parent/core/api/pom.xml
sofa-ark-parent/core/common/pom.xml
sofa-ark-parent/core/exception/pom.xml
sofa-ark-parent/core/pom.xml
sofa-ark-parent/core/spi/pom.xml
sofa-ark-parent/pom.xml
sofa-ark-parent/support/ark-maven-plugin/pom.xml
sofa-ark-parent/support/ark-plugin-maven-plugin/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-common-springboot/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
sofa-ark-parent/support/ark-support-starter/pom.xml
sofa-ark-parent/support/ark-tools/pom.xml
sofa-ark-parent/support/pom.xml
sofa-ark-plugin/config-ark-plugin/pom.xml
sofa-ark-plugin/web-ark-plugin/pom.xml

update to 2.1.3

---

sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
sofa-ark-parent/support/ark-maven-plugin/src/test/java/com/alipay/sofa/ark/boot/mojo/RepackageMojoTest.java

The Detail in issue #669 
set the settingsFile location when the config file exists
Fixes #669

fix: resolve the issue of dependency:tree execution failure

---

pom.xml
sofa-ark-bom/pom.xml
sofa-ark-parent/assembly/pom.xml
sofa-ark-parent/core-impl/archive/pom.xml
sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/DirectoryContainerArchive.java
sofa-ark-parent/core-impl/container/pom.xml
sofa-ark-parent/core-impl/pom.xml
sofa-ark-parent/core/api/pom.xml
sofa-ark-parent/core/common/pom.xml
sofa-ark-parent/core/common/src/test/java/com/alipay/sofa/ark/common/util/ClassLoaderUtilTest.java
sofa-ark-parent/core/exception/pom.xml
sofa-ark-parent/core/pom.xml
sofa-ark-parent/core/spi/pom.xml
sofa-ark-parent/pom.xml
sofa-ark-parent/support/ark-maven-plugin/pom.xml
sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/MavenUtils.java
sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
sofa-ark-parent/support/ark-maven-plugin/src/test/java/com/alipay/sofa/ark/boot/mojo/RepackageMojoTest.java
sofa-ark-parent/support/ark-plugin-maven-plugin/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-common-springboot/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
sofa-ark-parent/support/ark-support-starter/pom.xml
sofa-ark-parent/support/ark-tools/pom.xml
sofa-ark-parent/support/ark-tools/src/main/java/com/alipay/sofa/ark/tools/ArtifactItem.java
sofa-ark-parent/support/pom.xml
sofa-ark-plugin/config-ark-plugin/pom.xml
sofa-ark-plugin/web-ark-plugin/pom.xml

Support plugin exclude url

---

pom.xml
sofa-ark-bom/pom.xml
sofa-ark-parent/assembly/pom.xml
sofa-ark-parent/core-impl/archive/pom.xml
sofa-ark-parent/core-impl/container/pom.xml
sofa-ark-parent/core-impl/pom.xml
sofa-ark-parent/core/api/pom.xml
sofa-ark-parent/core/common/pom.xml
sofa-ark-parent/core/exception/pom.xml
sofa-ark-parent/core/pom.xml
sofa-ark-parent/core/spi/pom.xml
sofa-ark-parent/pom.xml
sofa-ark-parent/support/ark-maven-plugin/pom.xml
sofa-ark-parent/support/ark-plugin-maven-plugin/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-common-springboot/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
sofa-ark-parent/support/ark-support-starter/pom.xml
sofa-ark-parent/support/ark-tools/pom.xml
sofa-ark-parent/support/pom.xml
sofa-ark-plugin/config-ark-plugin/pom.xml
sofa-ark-plugin/web-ark-plugin/pom.xml

change version to 2.2.1

---

sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/test/jar/JarUtilsTest.java

remove invalid package #685

---

sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/biz/BizFactoryServiceImpl.java
sofa-ark-parent/core/common/src/test/java/com/alipay/sofa/ark/common/util/ClassLoaderUtilTest.java
sofa-ark-parent/core/spi/src/test/java/com/alipay/sofa/ark/spi/argument/LaunchCommandTest.java

fix_unit_test for classloaderUtilTest

fix_unit_test

---

sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/ArkServiceContainer.java
sofa-ark-parent/core/api/src/main/java/com/alipay/sofa/ark/api/ArkClient.java

for arklet query plugin
add `pluginManagerService` in `ArkClient`
maybe should push on the Maven Repository

update arkclient (add pluginManagerService for arklet)

---

sofa-ark-bom/pom.xml
sofa-ark-parent/core-impl/archive/pom.xml
sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/jar/JarUtils.java
sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/test/jar/JarUtilsTest.java

When maven-archiver/pom.properties file not exist, try to parse artifact id from local pom.xml file 
Resolved or fixed #720

Load artifact id from pom.xml file

---

sofa-ark-bom/pom.xml
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/web/EmbeddedServerService.java
sofa-ark-plugin/web-ark-plugin/pom.xml
sofa-ark-plugin/web-ark-plugin/src/main/java/com/alipay/sofa/ark/web/embed/WebPluginActivator.java
sofa-ark-plugin/web-ark-plugin/src/main/java/com/alipay/sofa/ark/web/embed/tomcat/ArkTomcatEmbeddedWebappClassLoader.java
sofa-ark-plugin/web-ark-plugin/src/main/java/com/alipay/sofa/ark/web/embed/tomcat/EmbeddedServerServiceImpl.java
sofa-ark-plugin/web-ark-plugin/src/test/java/com/alipay/sofa/ark/web/embed/WebPluginActivatorTest.java
sofa-ark-plugin/web-ark-plugin/src/test/java/com/alipay/sofa/ark/web/embed/tomcat/ArkTomcatEmbeddedWebappClassLoaderTest.java
sofa-ark-plugin/web-ark-plugin/src/test/java/com/alipay/sofa/ark/web/embed/tomcat/EmbeddedServerServiceImplTest.java

Add ut to tomcat plugin to achieve 95% code coverage

---

conf/javax.json
pom.xml

add package steps

---

pom.xml
sofa-ark-bom/pom.xml
sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/EmbedClassPathArchiveTest.java
sofa-ark-parent/support/ark-plugin-maven-plugin/src/main/resources/META-INF/maven/plugin.xml
sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/listener/ArkApplicationStartListener.java
sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/loader/CachedLaunchedURLClassLoader.java
sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/loader/JarLauncher.java
sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/test/java/com/alipay/sofa/ark/springboot/loader/CachedLaunchedURLClassLoaderTest.java
sofa-ark-plugin/web-ark-plugin/pom.xml

Suit 3.2.0

---

sofa-ark-bom/pom.xml
sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/DirectoryContainerArchive.java
sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
sofa-ark-plugin/config-ark-plugin/pom.xml

update guava or netty

---

pom.xml
sofa-ark-bom/pom.xml
sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/jar/JarURLConnectionTest.java
sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/web/ArkNettyWebServer.java
sofa-ark-plugin/netty-ark-plugin/pom.xml
sofa-ark-plugin/web-ark-plugin/pom.xml

update to 2.2.8-SNAPSHOT

---

sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/ArkServletLegacyAutoConfiguration.java
sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/resources/META-INF/spring.factories
sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports

适配 springboot 2.1.9
- 添加 ArkServletLegacyAutoConfiguration
- 根据类是否存在，使用 ArkServletLegacyAutoConfiguration 或 ArkServletAutoConfiguration
适配 springboot 2.1.9

adapt to springboot 2.1.9

---

sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/ArkServletLegacyAutoConfiguration.java
sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/loader/CachedLaunchedURLClassLoader.java

<fix> modify notes for javadoc

---

sofa-ark-plugin/config-ark-plugin/pom.xml
sofa-ark-plugin/netty-ark-plugin/pom.xml
sofa-ark-plugin/web-ark-plugin/pom.xml

fix ark plugin 

---

sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/model/BizModelTest.java
sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/model/BizInfo.java

* 优化显示
* fix as bizStateRecords
* 更新显示
(cherry picked from commit 1bf42178545af6095c093da9f5e1dac4c7bb35a6)

优化biz信息显示 (#897)

---

sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/ModuleSlimStrategy.java
sofa-ark-parent/support/ark-maven-plugin/src/test/java/com/alipay/sofa/ark/boot/mojo/ModuleSlimStrategyTest.java

* 黑白名单支持All配置方式
* 补单测
* 格式化
---------
Co-authored-by: hxk <h911623516@gmail.com>
Co-authored-by: leo james <leojames.googol@gmail.com>
(cherry picked from commit 71a1c471ff1a7fae9901c6bf1dacb015b74acd76)

黑白名单支持All的更新 (#985)

---

sofa-ark-parent/support/ark-tools/src/main/java/com/alipay/sofa/ark/tools/MainClassFinder.java

fix: support asm9 for jdk21 when packaging biz

---

pom.xml

to 2.3.1_SNAPSHOT
